### ISSUE TITLE
What exactly goes in the data field?

### ISSUE THREAD

**Issue by jlstr** [ethereumjs/ethereumjs-tx#103]
https://github.com/ethereumjs/ethereumjs-tx/blob/a73cc663b6f46b995a9b1be1e18ac8dc4d89d2f0/examples/transactions.js#L15

Moreover, how can I interact with a Contract's non-constant method? How can I sign such a method call?

**Comment by holgerd77** [comment]
Information on this can easily be found on Google, please don't misuse the issue tracker as a support forum and use e.g. the Gitter channel for stuff like this https://gitter.im/ethereum/ethereumjs. The better you describe your issue the greater the chance that someone will be willing to help there.

Will close this one here.
