### ISSUE TITLE
How get unsigned transaction (hex string) ?

### ISSUE THREAD

**Issue by Lursun** [ethereumjs/ethereumjs-tx#120]
How get unsigned transaction (hex string) and from unsigned transaction(hex string) to signed transaction ?
```js
let tx1=new EthereumTx({from:'0x',to:'0x',value:'0',gasLimit,.....});
let hexTx = tx1.????;

let tx2 = EthereumTx.from(hexTx) // ?????
tx2.sign(privateKey) 
tx2.serialize() 
```

**Comment by holgerd77** [comment]
You have to provide context on what is not working for you, e.g. by providing the console output you get.

**Comment by danjm** [comment]
@Lursun The example in this repo (https://github.com/ethereumjs/ethereumjs-tx/blob/master/examples/transactions.js) walks through how to create an ethereumjs-tx instance, edit the transaction data and then sign it with a private key.

If you wish to send that transaction over a network, you likely want to use web3. This example should be helpful in that case: https://github.com/ethereum/wiki/wiki/JavaScript-API#example-46
