### ISSUE TITLE
send data as a transaction

### ISSUE THREAD

**Issue by syrakozz** [ethereumjs/ethereumjs-tx#134]
i have a file pdf i need to submitted to blockchain when i should put it in the VALUe or DATA parameter in TX object and how i should convert it

**Comment by holgerd77** [comment]
Please don't use the issue tracker as a support forum, this is meant to file bugs or discuss library improvements.

You can try on [Gitter](https://gitter.im/ethereum/ethereumjs) if there is anyone within the community who can help you with your issue.
