### ISSUE TITLE
Simplify Transaction constructor's options

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-tx#149]
There are multiple ways to set the chain that a transaction belongs to, this can/should be simplified. 

I'm opening this issue as a continuation of the discussions that happened [here](https://github.com/ethereumjs/ethereumjs-tx/pull/131#issuecomment-478304415), [here](https://github.com/ethereumjs/ethereumjs-tx/pull/145#discussion_r278845954), and [here](https://github.com/ethereumjs/ethereumjs-tx/pull/145#discussion_r278847889).

**Comment by holgerd77** [comment]
Another question I have related to this: how justified is this constructor option split into "data" and "opts" dictionaries?

**Comment by alcuadrado** [comment]
I think they were separated because of how `defineProperties` work. But I don't have enough knowledge about the history of this library.

**Comment by holgerd77** [comment]
@alcuadrado ah ok, I think I already stumbled upon that one but forgot again, thanks!
