### ISSUE TITLE
new EthTx and signing produces incompatible tx

### ISSUE THREAD

**Issue by slothbag** [ethereumjs/ethereumjs-tx#15]
I stumbled across this problem using eth-lightwallet, narrowed it down to this library..

I create a new raw tx then sign it with a private key, I then send it onto geth using eth_sendRawTransaction.  It gets accepted by geth, and I can see the new Tx hash in the console, however the "to:" address looks like `to: &b6d5086e46d1b0e` instead of `to: 0xb6d5086e46d1b0e`

The tx never gets confirmed

**Comment by wanderer** [comment]
hmm, did you set the gas price?

**Comment by slothbag** [comment]
yup

```
		var txObject = {
			to: toAddress,
			gasLimit: web3.toHex(100000),
			gasPrice: web3.toHex(20000000000), //20 gwei
			value: web3.toHex(amount),
			nonce: web3.toHex(new Date().getTime())
		}
```

**Comment by wanderer** [comment]
i just ran this script https://gist.github.com/wanderer/1792fd405e9f1663b0f9 and it worked on geth. Can you try it and see of that works? also what does web3.toHex give back exactly?

**Comment by slothbag** [comment]
I tried your example, filling in the blanks like private key and replacing the nonce.. same problem, geth shows `to: &123456789`

**Comment by slothbag** [comment]
geth 1.3.5 and geth 1.4.0-unstable.

transactions via web3.js still work fine

**Comment by slothbag** [comment]
Unfortunately I don't have another way to generate a raw tx hex string so I can determine if the problem is with the hex string generated or eth_sendRawTransaction/geth

**Comment by wanderer** [comment]
can you post the serialized transaction?

**Comment by slothbag** [comment]
Here's the hex version

`f86d86015362fd3c698504a817c80082520894b6d5086e46d1b0e253d645c046e5e468221b8ac0830f4240801ca0430b29c18b57b51aad0202814d164ce95d545dca69e914deaebb2a5c081714d0a01635b842a1c0bb20401a8c6160a9619e44e92d1c0a20e6e8d3d48a2516b19770`

**Comment by karalabe** [comment]
The nonce seems to be 1457654676585 based on that hex dump. That cannot really be correct :P Nonces must be sequential from 0 on the main network or from 2^20 on the test network. Could you please double check that it's correct?

**Comment by slothbag** [comment]
Thanks, that seems to be the problem. It seems the & in geth was a red herring.
