### ISSUE TITLE
Error: Node error: {"code":-32000,"message":"invalid sender"

### ISSUE THREAD

**Issue by jdiegosierra** [ethereumjs/ethereumjs-tx#165]
I get this error making a typic signed call method transaction when I use _ethereumjs-tx_ version 2.0.0, however It works well with  1.3.7.

PD. When I was working in geth node I also tryed settng the values of ChainID and NetworkID to the same value.

`Error: Node error: {"code":-32000,"message":"invalid sender"}`

Library versions:
   node v10.15.3
  "web3": "^1.0.0-beta.55"
  "ethereumjs-tx": "^2.0.0"

My code:

```JavaScript

// Neither of them works
//let web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/v3/c84e1407efba4b8e937804dbe25f92ba"));
let web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8504")); // Geth node


    web3.eth.getGasPrice().then((gasPrice) => {
        web3.eth.getTransactionCount(wallet, 'pending').then((nonce) => {
            let txParams = {
                nonce: web3.utils.toHex(nonce),
                gasLimit: web3.utils.toHex(gasLimit),
                gasPrice: web3.utils.toHex(gasPrice),
                from: wallet,
                to: contract,
                data: data,
                // chainId: web3.utils.toHex(3),
            }
            let tx = new Tx(txParams);
            let privKey = Buffer.from(key, 'hex');
            tx.sign(privKey);
            tx = "0x" + tx.serialize().toString('hex')
            web3.eth.sendSignedTransaction(tx)
                .on('transactionHash', (hash) => {
                    console.log(hash);
                })
                .on('receipt', (receipt) => {
                    console.log(receipt);
                })
                .on('confirmation', (confirmationNumber, receipt) => {
                    console.log( confirmationNumber);
                    console.log(receipt);
                })
                .on('error', console.error);
        })
    });
```

**Comment by holgerd77** [comment]
@jdiegosierra Thanks for reporting this!

We have an apparent issue on too restrictive chain settings for `v2.0.0` - originally caused within the chain/HF selecting Common library - see linked issue above - this here might be related.

What is `PD` as abbreviation? Do you think the network and chain ID setting you did is related here or did you mentioned this as a separate thing? To what values did you try to set this? What happened?

Thanks!

**Comment by jdiegosierra** [comment]
Ups. Sorry.. PD means "Post Scriptum" in Spanish. Just a mistake!

I triyed settng the values of ChainID and NetworkID to the same value because I read this https://github.com/ethereum/web3.js/issues/1040. I tryed all what they said in the issue but I always got the same error.

**Comment by sharf521** [comment]
const tx = new EthereumTx(txParams,{'chain':'ropsten'})

**Comment by alcuadrado** [comment]
Hola @jdiegosierra! 

I just submitted a PR that has [an example of how to create ropsten transactions](https://github.com/ethereumjs/ethereumjs-tx/blob/4f3d3668125c0ede83f1f61537c78871d95aaf25/examples/ropsten-tx.ts). It's basically what @sharf521 :)

**Comment by jdiegosierra** [comment]
Thx @sharf521 & @alcuadrado !!

**Comment by Skyge** [comment]
Why should we specific the parameter: `chain` at the version 2.0.0, if I use 1.3.7, I do not have got to write the parameter: `chain`.

**Comment by alcuadrado** [comment]
Version 1.x had some really complicated logic to manage this, which lead to multiple bugs. v2 makes things more explicit, but also more robust.
