### ISSUE TITLE
the request of a dependency is an expression

### ISSUE THREAD

**Issue by PHPJourney** [ethereumjs/ethereumjs-tx#177]
WARNING in ./node_modules/web3-eth-accounts/src/scrypt.js
17:50-60 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/web3-eth-accounts/src/scrypt.js
 @ ./node_modules/web3-eth-accounts/src/index.js
 @ ./node_modules/web3-eth/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./src/utils/common.js
 @ ./src/main.js

I'm try use electron build. give me this warning . 

build completed can't runing.

How do this.

**Comment by alcuadrado** [comment]
This is a Web3.js issue, please report it [there](https://github.com/ethereum/web3.js/).
