### ISSUE TITLE
Invalid sender using for Ethereum Classic

### ISSUE THREAD

**Issue by jinglics** [ethereumjs/ethereumjs-tx#179]
Using offline-sign of ETC transaction, Get "Invalid sender" error when sending raw transaction to network.

How to set the parameters for ETC tx? In the older version, no parameter is required for ETC I remembered.

**Comment by holgerd77** [comment]
Hi @jinglics, not sure about the behavior before the `v2.0.0` release, but Ethereum Classic is not officially supported by this library. You might want to have a look into the [custom chain example code](https://github.com/ethereumjs/ethereumjs-tx/blob/master/examples/custom-chain-tx.ts), eventually initializing with the Ethereum Classic chain ID 61 helps? Would be nice if you can repost here your experiences.
