### ISSUE TITLE
npm install ethereumjs-tx fails

### ISSUE THREAD

**Issue by alexykot** [ethereumjs/ethereumjs-tx#18]
`npm install ethereumjs-tx` fails for me with the following [stack trace](https://gist.github.com/alexykot/ccc4beea78b1304dba51).

This happens inside Docker container based on `debian:jessie`, with `npm v3.7.3`, `nodejs v5.9.1`.

**Comment by axic** [comment]
You are using a **very** old version of ethereumjs-tx, which depends on `secp256k1@0.0.15`. `secp256k1` right now is at 3.1.0
