### ISSUE TITLE
TypeError: finished is not a function

### ISSUE THREAD

**Issue by olegabr** [ethereumjs/ethereumjs-tx#181]
Look at this issue for details please: https://github.com/trufflesuite/truffle/issues/2431

**Comment by alcuadrado** [comment]
This library has no `finished` method nor property. I don't see how this issue can belong here. Can you clarify, please?

**Comment by olegabr** [comment]
Maybe @eggplantzzz as an author of this fix (https://github.com/trufflesuite/truffle/pull/2438) can clarify here.

**Comment by eggplantzzz** [comment]
@olegabr Actually this is an issue with Truffle. In Truffle, `ethereumjs-tx` was bumped a major version without the necessary adjustments to the surrounding code, thus introducing a bug. This is not an issue with `ethereumjs-tx`. :)

**Comment by olegabr** [comment]
@eggplantzzz, Thank you for explanation!
