### ISSUE TITLE
Transaction.sign failed in other browser except chrome - ECMAScript 6 new feature not supported

### ISSUE THREAD

**Issue by arthew** [ethereumjs/ethereumjs-tx#20]
Reference: [https://github.com/ethereumjs/browser-builds/issues/1](https://github.com/ethereumjs/browser-builds/issues/1)

In transaction.sign, the "Object.assign" be used to merge object attributes which is new feature of ECMAScript 6 and had not supported by most type of browser.

In fact, it's not necessary to do that, we can assign attributes value simply here.

**Comment by kumavis** [comment]
please use the polyfill listed here https://github.com/ethereumjs/ethereumjs-tx/pull/17
