### ISSUE TITLE
how get privateKey

### ISSUE THREAD

**Issue by 362228416** [ethereumjs/ethereumjs-tx#30]
I want use this module send transaction, but I can't get a private key, I has a geth client, and has many address and pass, but has no private key, How get it ?

**Comment by wanderer** [comment]
there  are lots of ways generate a private key. Here is one of the simplest. (not necessary secure)
```
var crypto = require('crypto')
var privateKey = crytpo.randomBytes(32)

```
ethereumjs-tx allows you to sign with an `Buffer` or `Uint8Array` of the length 32

**Comment by wanderer** [comment]
and let me know if that works for :)

**Comment by 362228416** [comment]
this private key is safe？

**Comment by wanderer** [comment]
it gets the entropy from the OS... so "maybe". What you can do to make it safer is run it through a KDF a couple of times and combine it with other sources for entropy. 

You could use some like this https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback

Where your password here would be the `privateKey`

**Comment by 362228416** [comment]
last question , how generate publicKey use this privateKey, I need use it receive transaction, and use privateKey send transaction.?

**Comment by 362228416** [comment]
@wanderer help

**Comment by wanderer** [comment]
@362228416 you can use [ethereumjs-util](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/index.md#privatetoaddress).

```
var ethUtil = require('ethereumjs-util')
var ethereumAddress = ethUtil.privateToAddress(my_private_key)
```
