### ISSUE TITLE
call sendTx ,  Data seems to be correct, but no effect

### ISSUE THREAD

**Issue by 362228416** [ethereumjs/ethereumjs-tx#32]
I  was create a transaction,  use the following code:

```
var Tx = require('ethereumjs-tx')
var rawTx = {
  nonce: '0x100004',
  gasPrice: '0x4a817c800',  //0.00000002
  gasLimit: '0x15f90', //90000
  from: '0x1911c081b0a2359d77d1f858bf5b5b04a080f2bb',
  to: '0x5f56bba9ee673d0c7bccf4be1a78b9db3a51114d',
  value: '0x2386f26fc10000',   // 0.01
  data: '0x'
}
var tx = new Tx(rawTx)
tx.sign(privateKey)

var serializedTx = tx.serialize()
var signData = serializedTx.toString('hex');
console.log(signData)
```

output tx data

f86f831000048504a817c80083015f90945f56bba9ee673d0c7bccf4be1a78b9db3a51114d872386f26fc10000801ba08aacd5525b240df3149ead81c2fd4bf3d2c01cc81506a5442f727f92850c4935a07807e5a74e1994a4fce6727fa9422e34d5da83411a8065c14249e9b5845cac3e

then Broadcast Raw Transaction on http://testnet.etherscan.io/pushTx

show following message 
```
{ "jsonrpc": "2.0", "id": 1, "result": "0x15b9ff6eca21cfe48e853458908abf53ccae131a9aeb4eb03d553281c77c1f89" }
```

but, I open the http://testnet.etherscan.io/tx/0x15b9ff6eca21cfe48e853458908abf53ccae131a9aeb4eb03d553281c77c1f89   , it can found, why?

In addition, I try call sendRawTransaction in the geth console with --testnet
```
eth.getTransaction(eth.sendRawTransaction('f86f831000048504a817c80083015f90945f56bba9ee673d0c7bccf4be1a78b9db3a51114d872386f26fc10000801ba08aacd5525b240df3149ead81c2fd4bf3d2c01cc81506a5442f727f92850c4935a07807e5a74e1994a4fce6727fa9422e34d5da83411a8065c14249e9b5845cac3e'))
```
return the info following
```
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000
",
  blockNumber: null,
  from: "0x1911c081b0a2359d77d1f858bf5b5b04a080f2bb",
  gas: 90000,
  gasPrice: 20000000000,
  hash: "0x15b9ff6eca21cfe48e853458908abf53ccae131a9aeb4eb03d553281c77c1f89",
  input: "0x",
  nonce: 1048580,
  to: "0x5f56bba9ee673d0c7bccf4be1a78b9db3a51114d",
  transactionIndex: null,
  value: 10000000000000000
}
``` 

All the operation in the test network, Data seems to be correct, but no effect, What did I missed?

**Comment by 362228416** [comment]
@wanderer help.

**Comment by 362228416** [comment]
it work! thanks.

**Comment by mtbitcoin** [comment]
may i know what did you do to get this working?

**Comment by himanshuoodles** [comment]
How you solved that please mention?
