### ISSUE TITLE
Documentation for creating contracts

### ISSUE THREAD

**Issue by superphly** [ethereumjs/ethereumjs-tx#50]
The documentation shows some example code for creating a transaction that sends ether from one account to another but it doesn't show how to create a contract tx. I was hoping someone could show some code on how that's done.

In addition, how does one export a signed tx for use on a networked machine. I ask this, because I'm trying to create a console for airgapped machines.

**Comment by fanatid** [comment]
You can pass contract code to `data` in Transaction params: https://github.com/ethereumjs/ethereumjs-tx/blob/188484c4be1c3cd9e6c1b98d487de9e0d922e84c/index.js#L31
How create data for contract is not related with this repository, read ethereum docs and you find all answers.

When tx will be signed you can serialize it and push/parse on other machine `tx.serialize().toString('hex')` -- return serialized tx (rlp encoded data) in HEX.

**Comment by kumavis** [comment]
one more note, omit the `to` field in the txParams when preparing a contract publish
