### ISSUE TITLE
AssertionError: The field v must have byte length of 1  on this line "  tx.sign(privateKey);" IN Private geth chain

### ISSUE THREAD

**Issue by himanshuoodles** [ethereumjs/ethereumjs-tx#52]
[I have this code , i want to already signed transaction for ethereum .

> ERROR COMING IN LINE:  AssertionError: The field v must have byte length of 1
>     at Transaction.setter [as v] (node_modules/ethereumjs-util/index.js:609:9)
> 

  let resData = {};
            var Tx = require('ethereumjs-tx');
            var privateKey = Buffer.from('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex');
            var gasPrice = privateWeb3.eth.gasPrice;
            var gasPriceHex = privateWeb3.toHex(gasPrice);
            var nonce = privateWeb3.eth.getTransactionCount(req.body.fromAddress);
            var nonceHex = privateWeb3.toHex(nonce);
            var rawTx = {
                nonce: nonceHex,
                gasPrice: gasPriceHex,
                gasLimit: '0x2710',
                to: req.body.toAddress,
                from: req.body.fromAddress,
                value: '0x00',
                data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
            }

            var tx = new Tx(rawTx);
            tx.sign(privateKey);

            var serializedTx = tx.serialize();

            //console.log(serializedTx.toString('hex'));
            

            privateWeb3.eth.sendRawTransaction(serializedTx.toString('hex'), function(err, hash) {
                //  if (!err)
                console.log("hiii", err, hash); // "0x7f9fade1c0d57a7af66ab4ead79fade1c0d57a7af66ab4ead7c2c2eb7b11a91385"
            }); ](url)

says AssertionError: The field v must have byte length of 1 on this line "  tx.sign(privateKey);"

MY from and to both account are valid and both have balance . Why i am getting this error

**Comment by tinybike** [comment]
I am also getting this error in the latest (1.2.5) version of ethereumjs-tx.  (I was previously using 1.1.1, and did not encounter this error.)

**Comment by himanshuoodles** [comment]
This will help you @tinybike . http://ethereum.stackexchange.com/questions/12559/signing-raw-transaction-assertionerror-the-field-v-must-have-byte-length-of-1

**Comment by tinybike** [comment]
Thanks @himanshuoodles, that is indeed the problem -- test chain has a too-high chainId value.  Well I didn't realize there was a maximum value to network ID when I set it.

**Comment by himanshuoodles** [comment]
@tinybike  if you are using web3 can you send me privateWeb3.eth.sendRawTransaction whole process because i am in issue in "Error: Invalid sender
    at Object.InvalidResponse " .

**Comment by tinybike** [comment]
I'm unfortunately not using web3, so I can't help you debug directly... I'm using augur's custom middleware (https://github.com/AugurProject/ethrpc and https://github.com/AugurProject/augur.js) -- the relevant lines in augur.js are https://github.com/AugurProject/augur.js/blob/master/src/accounts.js#L281-L423 if that is helpful.

Are you getting that error when you try to `tx.sign()` or when you try to submit the raw tx?  Either way, what's the output of `console.log(tx.toJSON())`?

**Comment by himanshuoodles** [comment]
Then leave it . I will debug it .Thanks

**Comment by flyswatter** [comment]
This was also fixed in later versions of geth that support the EIP 155 fix, which tolerates much higher `v` values.
