### ISSUE TITLE
browserify with babelify

### ISSUE THREAD

**Issue by serapath** [ethereumjs/ethereumjs-tx#54]
I am having problems using ethereumjs-tx in the browser because of es2015 class syntax.
With browserify and babelify i can fix it and wonder if it would make sense to include in the `package.json` here:

```js
  "browserify": {
    "transform": [
      ["babelify", {
        "presets": ["es2015"]
      }]
  }
```
I imagine it doesnt make a difference unless someone is depending on `ethereumjs-tx` and wants to babelify the code to es5 for browser compatibility reasons.

It would also be possible to force a global transform, but I'm currently running into some issues with that and it could be solved if modules using es2015 would add required transforms to be picked up by browserify.

 (In order for the module that requires `ethereumjs-tx` and uses `browserify` to work, `babel-preset-es2015` and `babelify` would need to be installed, so maybe it's a good idea to add them to the dependencies)

**Comment by wanderer** [comment]
added and merges

**Comment by tinybike** [comment]
Hooray!
