### ISSUE TITLE
What is the tx data

### ISSUE THREAD

**Issue by EasonWang01** [ethereumjs/ethereumjs-tx#58]
```
const txParams = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
  // EIP 155 chainId - mainnet: 1, ropsten: 3
  chainId: 3
}
```

As the example,if we want to sign an transaction with the given field
```
1.private key
2.From account address 
3.To account address 
4.value
5.gas
```

why we need to give nonce and chainID and data?

How to using API to get this value?

**Comment by michbil** [comment]
@EasonWang01 Nonce is your transaction number. Every transaction should have incremented number(nonce). You can use API method web3.eth.getTransactionCount(sender Ethereum address) to get actual nonce.

**Comment by EasonWang01** [comment]
How to get the `chainID and data`

**Comment by michbil** [comment]
Data is your actual code to execute. Take a look at getData method in web3 documentation.
get chainId based on network you're going to use: main net or ropsten

**Comment by EasonWang01** [comment]
It only describe about contract data ,but how to compile eth transaction to data?I was using Private Network.

**Comment by michbil** [comment]
Contract.getData does the thing. Search web3 docs

**Comment by EasonWang01** [comment]
But it's not contract.
It's just a raw transaction.

**Comment by michbil** [comment]
getData generates raw transaction from your contract and contract parameters.

```
var token = this.web3.eth.contract(abi)
            .at(address,(err,res) => {...});
var data = token.donate.getData(... contract parameters ...);
```

**Comment by EasonWang01** [comment]
There is no contract，only transfer ether from A to B.

**Comment by michbil** [comment]
then data is empty i guess

**Comment by michbil** [comment]
Take a look at exisiting transactions sending ether, they have empty data field [](https://testnet.etherscan.io/tx/0x07dcb7534888fa92602a299bc5fde9e6bc6fdd79626c3e0340ea0cb1f2f4e844)

**Comment by 360disrupt** [comment]
@michbil 
1) If my method requires two params e.g. `contract.methods.methodA(param1, param2)` 
```
params = {
  param1Key: param1,
  param2Key: param2
}
const txParams = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  chainId: 1
}
would params go into `txParams` or `txParams.data`
```

2) The contract I'm using does not have a function `getData`, `contract.methods.methodA` exists but `contract.methods.methodA.getData` does not how do I get the params into the right format?
