### ISSUE TITLE
ES6 code breaks create-react-app build

### ISSUE THREAD

**Issue by miladmostavi** [ethereumjs/ethereumjs-tx#59]
Because of ES6 code used in this lib, unejected create-react-app applications break while building.
This lib is also used in eth-lightwallet, and the workaround I used was to add a `postinstall` script to my `package.json` that removes this lib from node_modules. I included this lib in my `src/vendor` directory, added src/vendor to `NODE_PATH` so that eth-lightwallet keeps working.

It would be nice if you had a build process that exposed the babelified ES5 version.

**Comment by tinybike** [comment]
Seconding this request.  Right now I have a script with this awful little hack in augur.js and ethrpc to compile their distributables:
```
./node_modules/.bin/babel ./node_modules/ethereumjs-tx --source-root ./node_modules/ethereumjs-tx  -d ./node_modules/ethereumjs-tx
```

**Comment by captDaylight** [comment]
@tinybike Can you elaborate how to implement this hack? I'm in the same boat...
