### ISSUE TITLE
Add ability to toggle EIP 155 replay protection

### ISSUE THREAD

**Issue by flyswatter** [ethereumjs/ethereumjs-tx#63]
I'm not sure if this is possible right now, but we have some users who are using old clients for private blockchains, that don't support EIP 155 replay protection, and cannot recognize the signatures from this module anymore.

It would be nice to have a way of defining whether or not to compute the signature in the new or old value.

**Comment by fanatid** [comment]
If I right understand the issue before signing you should set `_chainId` property to zero that give you signature in old format.

**Comment by flyswatter** [comment]
I tried that but wasn't able to verify the signature was the old format. I may just need a better verification strategy...

**Comment by fanatid** [comment]
Can you paste code for verify here?

**Comment by flyswatter** [comment]
The last assert in this file:
https://github.com/MetaMask/metamask-plugin/blob/i1357-ToggleEip155Protections/test/unit/tx-manager-test.js

**Comment by fanatid** [comment]
link to side project is not cool, if you want help please paste code which can be run as test

**Comment by flyswatter** [comment]
I pasted what I was able to from my phone, I can do something better later. I thought you just wanted to see how I was trying to validate.

**Comment by kumavis** [comment]
if `chainId` is 0, it will use the old signing style
https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L155
