### ISSUE TITLE
var EthereumTx = require('ethereumjs-tx') Unable to resolve module React-Native

### ISSUE THREAD

**Issue by rajkumariray** [ethereumjs/ethereumjs-tx#64]
Any One work for this in react-native app. I have install npm and in node modules i am able to find complete folder of ethereumjs-tx but still I am getting error "Unable to resolve module - 'ethereumjs-tx".

Below is my package.json

{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "buffer": "^5.0.6",
    "crypto": "0.0.3",
    "es6-shim": "^0.35.3",
    "ethereumjs-tx": "1.3.1",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "redux-thunk": "^2.2.0",
    "web3": "^0.19.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.1",
    "babel-preset-react-native": "^1.9.1",
    "jest": "20.0.1",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "app/assets/"
    ]
  }
}

**Comment by rajkumariray** [comment]
As this npm doesn't work at my end. I have found another substitute for this below are other npm which can help someone.
npm install ethjs-account , npm install ethjs-signer

**Comment by TaiPA** [comment]
How to solve this problem ?

**Comment by TaiPA** [comment]
Not find out why yet but if you just use `"ethereumjs-tx": "1.3.1",` it will be OK on react-native 0.45.1

**Comment by rajkumariray** [comment]
I am in hurry with my project in react-native so we have found another solution on npm i.e. ethjs-account to connect ethereum. If you see my package.json, I have already used ethereumjs-tx": "1.3.1 but still it didn't resolve my issue.

**Comment by infinityblockchainlabs** [comment]
@rajkumariray 
Sorry, my type mistake, `"ethereumjs-tx": "1.3.0",` is correct.
I not try ethjs-account jet. Will try in future.

**Comment by themotu** [comment]
Issue still exists

**Comment by siner9586** [comment]
> var Tx = require('ethereumjs-tx');
undefined
**### > Tx = require('ethereumjs-tx');
[Function: Transaction]**
