### ISSUE TITLE
Uncaught TypeError: (intermediate value).toNumber is not a function

### ISSUE THREAD

**Issue by itisBaga** [ethereumjs/ethereumjs-tx#65]
After trying `const tx = new EthereumTx(txParams);` I received error:

Uncaught TypeError: (intermediate value).toNumber is not a function
    at Object.exports.bufferToInt (main.js:164067)
    at new Transaction (main.js:163711)
    at main.js:78715
    at main.js:58915
    at main.js:185514
    at main.js:185550
    at main.js:185550
    at run (main.js:181001)
    at runIfPresent (main.js:181030)
    at onGlobalMessage (main.js:181070)

**Comment by fanatid** [comment]
can you provide `txParams`?

**Comment by itisBaga** [comment]
Sure.

`let txParams = {
                nonce: this.web3.toHex(this.web3.eth.getTransactionCount('0x' + fromAddress)), // 'b52ead32f0e1ed3530207933a208fe097f6faebf' 
                gasPrice: params.gasPrice, //'0x0'
                gas: params.gas, // '0x0'
                from: '0x' + fromAddress, // 'b52ead32f0e1ed3530207933a208fe097f6faebf' 
                to: currency, // '0xefcc9f9a5cb3d6062c18eeffdf90a29bb771fccc'
                value: params.value, // '0x0'
                data: this.contractInstance.sendFunds.getData('0x' + fromAddress, '0x' + toAddress, parseFloat(value) * 100), // also here is normal addresses
                chainId: params.chainID // 0
            };`

0x0 is ok because we used private node without gas

**Comment by fanatid** [comment]
please provide `txParams` like object which can be used for receiving error
respect time of other people

**Comment by itisBaga** [comment]
Okau. I have updated object. But It's call to smart contract in private node. So in mainnetwork gas params should be another.

**Comment by fanatid** [comment]
this params are valid for 1.2.5, which version you are using?

**Comment by itisBaga** [comment]
Latest version 1.3.1

**Comment by fanatid** [comment]
1.3.1 also works...

**Comment by itisBaga** [comment]
Thank you. Will try to find a bug in other libraries.

**Comment by fanatid** [comment]
Will close it for now, feel free to reopen if you find fixture for such error.

**Comment by itisBaga** [comment]
Problem was at bn.js It ddidn't istalled automatically.

**Comment by fanatid** [comment]
how so?

**Comment by itisBaga** [comment]
Not sure, but after hours of debugging I found that BN object from Bignumber lib is not defined. Installation of bn.js solved the problem.
