### ISSUE TITLE
Parse and verify transaction

### ISSUE THREAD

**Issue by MitchK** [ethereumjs/ethereumjs-tx#68]
Hi,

After I created a raw transaction, how can I 

1. Deserialize the transaction from a hex string
2. Verify the signature?
3. Parse the arguments from the transaction?

**Comment by MitchK** [comment]
Found the solution. You need the ```rlp``` module to decode the transaction string first:

```
const rawTxStr = '0x...'
const decodedRawTx = rlp.decode(rawTxStr)
const tx = new Transaction(decodedRawTx)
console.log(tx.verifySignature())

**Comment by etherCrossroads** [comment]
please how can i import rlp module?

**Comment by danjm** [comment]
@etherCrossroads see installation instructions and usage example here: https://github.com/ethereumjs/rlp#install
