### ISSUE TITLE
How to browserify?

### ISSUE THREAD

**Issue by jefffreey** [ethereumjs/ethereumjs-tx#69]
Whenever I try to browserify `require('ethereumjs-tx')` (or any other module that depends on it), I get the following error:

> Error: Couldn't find preset "stage-0" relative to directory "/[app]/node_modules/ethereumjs-tx" while parsing file: /[app]/node_modules/ethereumjs-tx/index.js

How can I browserify this module?

Thanks

**Comment by kumavis** [comment]
i just got this

seems that since we are exporting es5/index.js
https://github.com/ethereumjs/ethereumjs-tx/blob/master/package.json#L5

we shouldn't have the browserify transform in package.json

cc @tinybike

**Comment by kumavis** [comment]
I resolved this by adding `.babelrc` to npmignore and removing the browserify transform from package.json

fixed in `1.3.3`
