### ISSUE TITLE
Rename parameters to match RPC serialization

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-tx#7]
the names are different so i need some boilerplate and i also forget that the keys change sometimes and trip over that

would be nice to just drop it in

rpc results:
```
   ├─ transactions
   │  └─ 0
   │     ├─ hash: 0xf365d4ddd7bf0c527bee73676df632cf738d43b287865424dee226e9d9794e3d
   │     ├─ nonce: 0xbcbc
   │     ├─ blockHash: 0x12b82561ed2fe63f306b5178a545622512d74e3aed9fd53500484bb3e2c8335b
   │     ├─ blockNumber: 0x9b924
   │     ├─ transactionIndex: 0x0
   │     ├─ from: 0x2a65aca4d5fc5b5c859090a6c34d164135398226
   │     ├─ to: 0xc65e24227e40a6a0be5c5cf1f0f120c2310e9f7a
   │     ├─ value: 0x43f33b195cdbf000
   │     ├─ gas: 0x15f90
   │     ├─ gasPrice: 0xba43b7400
   │     └─ input: 0x
```

my boilerplate:
```js
function materializeTransaction(data){
  var tx = new Transaction({
    nonce: data.nonce,
    gasPrice: data.gasPrice,
    gasLimit: data.gas,
    to: data.to,
    value: data.value,
    data: data.input,
  })
  tx.from = new Buffer(ethUtil.stripHexPrefix(data.from), 'hex')
  return tx
}
```

**Comment by wanderer** [comment]
so we just need to change?
* gasLimit -> gas
* data -> input

input is the weird one. Where is that coming from? Can we rename input to data?

**Comment by wanderer** [comment]
@kumavis

**Comment by kumavis** [comment]
These are coming from the RPC running against geth. I like `data` better than `input` and I also like `gasLimit` better than `gas`... hmm maybe just some options in the constructor that will check for these keys as well?

**Comment by wanderer** [comment]
or add aliases. But doing that mean modifying  [defineProp](https://github.com/ethereumjs/ethereumjs-util/blob/37971507cc9a5c9ad7c9bad59ecd7f2e4a7f0db1/index.js#L417-L495). I have been wanting to remove defineProp and replace it with an independent module. Related https://github.com/ethereumjs/ethereumjs-util/issues/18

**Comment by kumavis** [comment]
we should also confirm cpp-eth and any other rpc clients behave the same

**Comment by wanderer** [comment]
@kumavis I added alias for the above properties

**Comment by kumavis** [comment]
fantaaastico :dancer:
