### ISSUE TITLE
es5 doesn't seem to output

### ISSUE THREAD

**Issue by captDaylight** [ethereumjs/ethereumjs-tx#73]
After looking at #62 it seems like the build is still output as es6. Could it be because the .babelrc has been added to the .npmignore?

**Comment by axic** [comment]
It was changed with https://github.com/ethereumjs/ethereumjs-tx/commit/32dc30ed772f7064c92c8c652a1cbf0fb4e88a24.

@kumavis ?

**Comment by captDaylight** [comment]
maybe the build command wasn't run before it was published to npm?

**Comment by holgerd77** [comment]
No complaints on this for a longer time, will close.
