### ISSUE TITLE
Deterministic sign

### ISSUE THREAD

**Issue by pernas** [ethereumjs/ethereumjs-tx#76]
If I am not wrong, the signing process seems to use an RNG that way not implementing the deterministic signing process that other libraries like bitcoinjs implement. Is there any reason for that? Are there plans to change it to the standard deterministic signature?

Thanks

**Comment by fanatid** [comment]
O_O where you found RNG in signing?

**Comment by pernas** [comment]
Maybe I am following something wrong.

This is ethereumjs sign:
https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L227-L238
which calls:
 https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L321-L335 
and goes to:
https://github.com/cryptocoinjs/secp256k1-node/blob/master/lib/elliptic/index.js#L180-L202
and ends up in:
https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L89-L152
which given that options.k is missing calls
`new BN(drbg.generate(this.n.byteLength()))` that seems to be a pseudo-random generator.

But as I said... maybe I am following something wrong

**Comment by pernas** [comment]
Well, I did not saw that parameter options is mutated here:
https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L91

Hence, `options.k` should be this function here:
https://github.com/cryptocoinjs/secp256k1-node/blob/master/lib/elliptic/index.js#L183-L187

But on this call here there is no third parameter so I understand that nonceFn seems to be undefined:
https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L328

So, not clear to me which branch is finally running here:
https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L120

**Comment by fanatid** [comment]
`drbg` is deterministic random bit generator
"random" number `k` (nonce) depends from initial values
algorithm described here: https://tools.ietf.org/html/rfc6979#section-3.2

**Comment by pernas** [comment]
Thanks you very much for clarification and sorry for bothering you. I close that issue
