### ISSUE TITLE
Make setting "from" parameter less of a hack

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-tx#8]
Sometimes we want to record the `from` of a tx to be something we dont have a private key for. uses cases: ( simulation, testing, checking gasPrice ).

Normally the from is calculated from the signature, but theres a hack workaround to overwrite it yourself. The vm looks at `tx.from` to process the state transition.

it would be nice if we could make this less of a hack and incorporate it into the normal instantiation options.
```js
new Transaction({ from: '...' })
```

additionally, we could add a flag to check if the tx has been signed: `tx.isSigned //=> false`

**Comment by axic** [comment]
@kumavis you could still run a verifySignature and compare if the supplied `from` matches the address used to sign

**Comment by kumavis** [comment]
that should fail normally

**Comment by wanderer** [comment]
@kumavis `verifySignature`  i think is the equivalent of `isSigned`

**Comment by wanderer** [comment]
@kumavis do you have any suggestions on how to improve the situation? This [piece of logic](https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L95-L98) is broken already

**Comment by kumavis** [comment]
@wanderer whats broken about it?

**Comment by kumavis** [comment]
I agree `verifySignature` is enough and we dont need a `isSigned` flag

**Comment by wanderer** [comment]
if you sign, then sign again with a different privateKey the from won't update

**Comment by kumavis** [comment]
oh!

**Comment by wanderer** [comment]
no!

**Comment by wanderer** [comment]
closed; we now have fake.js that takes care of this.
