### ISSUE TITLE
Create a signed transaction with r/s/v values instead of private key

### ISSUE THREAD

**Issue by eswak** [ethereumjs/ethereumjs-tx#85]
Hi guys,

I'm trying to sign transactions in the browser using your module and [LedgerHQ/ledger-node-js-api](https://github.com/LedgerHQ/ledger-node-js-api).

The private key is unknown to me, but their library provides the `r`/`s`/`v` values that should be used for signing the transaction.

I'm not sure why the signature is invalid using the following code, but maybe you guys can see where the problem is ?

```js
var raw = {
  "nonce": "0x1",
  "gasPrice": "0x2cb417800",
  "gasLimit": "0x5208",
  "to": "0x6ef71ca9cd708883e129559f5edbfb9d9d5c6148",
  "value": "0x5af3107a4000",
  "chainId": 1
};

var txToSign = new ethereumjs.Tx(raw).serialize().toString('hex');

new ledger.eth(comm).signTransaction_async('44\'/60\'/0\'/0', txToSign).then(function(result) {
  raw.r = '0x' + result.r; // "0xf4611d559d1db7c034236ef3989b43304b2e8ffd5855cead12da8f8f10c1db4f"
  raw.s = '0x' + result.s; // "0x68acbc380b551cd883db4b995f50df01533efef09f2529d85d205a6dd83e8f43"
  raw.v = '0x' + result.v; // "0x5b"

  var txSigned = new ethereumjs.Tx(raw);

  console.log('tx raw', raw);
  console.log('tx signed', txSigned.serialize().toString('hex')); // 0xf86a018502cb417800825208946ef71ca9cd708883e129559f5edbfb9d9d5c6148865af3107a4000805ba0f4611d559d1db7c034236ef3989b43304b2e8ffd5855cead12da8f8f10c1db4fa068acbc380b551cd883db4b995f50df01533efef09f2529d85d205a6dd83e8f43
  console.log('verifySignature', tx.verifySignature()); // false
}).catch(function() {});
```

I thought maybe the problem is because I don't call the `sign(privateKey)` function and [some handling of the chainId is done there](https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L235) ?

Thank you for your time,
Erwan

ps: I also created an issue on their repo : https://github.com/LedgerHQ/ledger-node-js-api/issues/43
even if no bug is found; I think it may be good to provide a more detailed documentation if we want to see more websites that provide ledger integration like myetherwallet

**Comment by holgerd77** [comment]
Did you do some debugging directly in the [verifySignature](https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L207) method (e.g. by inserting ``console.log`` output there) to see where exactly the signature verification fails? At the end on ``return !!this._senderPubKey``? Or already before?

**Comment by eswak** [comment]
Hi @holgerd77,

It stops right here : https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L210

I'm not sure what it means though...

**Comment by eswak** [comment]
Hi @holgerd77, thanks for your response !

I modified the verifySignature as follow to add `console.log` : 
```js
  Transaction.prototype.verifySignature = function verifySignature() {
    var msgHash = this.hash(false);
    console.log('verify signature : ', JSON.stringify({
      msgHash: msgHash,
      _senderPubKey: this._senderPubKey,
      _chainId: this._chainId,
      _homestead: this._homestead,
      r: this.r,
      v: this.v,
      s: this.s
    }, null, 2));
    console.log('new BN(this.s).cmp(N_DIV_2)', new BN(this.s).cmp(N_DIV_2));
    // All transaction signatures whose s-value is greater than secp256k1n/2 are considered invalid.
    if (this._homestead && new BN(this.s).cmp(N_DIV_2) === 1) {
      console.log('early return 1');
      return false;
    }

    try {
      var v = ethUtil.bufferToInt(this.v);
      console.log('ethUtil.bufferToInt(this.v)', ethUtil.bufferToInt(this.v));
      if (this._chainId > 0) {
        v -= this._chainId * 2 + 8;
      }
      console.log('v after subtract', v);
      this._senderPubKey = ethUtil.ecrecover(msgHash, v, this.r, this.s);
      console.log('this._senderPubKey after set', this._senderPubKey);
    } catch (e) {
      console.log('early return 2', e);
      return false;
    }

    console.log('!!this._senderPubKey', !!this._senderPubKey);
    return !!this._senderPubKey;
  };
```
it gives the following output : 
```
verify signature :  {
  "msgHash": {
    "type": "Buffer",
    "data": [
      130,
      139,
      7,
      61,
      197,
      99,
      17,
      97,
      202,
      193,
      57,
      87,
      209,
      75,
      68,
      241,
      254,
      201,
      70,
      64,
      35,
      59,
      87,
      151,
      152,
      96,
      246,
      202,
      175,
      97,
      148,
      106
    ]
  },
  "_senderPubKey": "04d419541b8ea57ed5cfeea769c54a79615924ab0185d0f0311ccea4faeed88375dd2204bbed6e0cc9d2cd3321bd8ead7ba74a4aa8e49bb30e74f439aed24aa192",
  "_chainId": 1,
  "_homestead": true,
  "r": {
    "type": "Buffer",
    "data": [
      184,
      181,
      124,
      107,
      12,
      55,
      249,
      255,
      66,
      152,
      131,
      198,
      149,
      250,
      52,
      172,
      239,
      48,
      89,
      100,
      82,
      252,
      149,
      241,
      72,
      58,
      221,
      55,
      6,
      115,
      120,
      189
    ]
  },
  "v": {
    "type": "Buffer",
    "data": [
      92
    ]
  },
  "s": {
    "type": "Buffer",
    "data": [
      99,
      158,
      44,
      152,
      83,
      195,
      58,
      215,
      45,
      187,
      40,
      88,
      228,
      248,
      74,
      235,
      246,
      163,
      249,
      251,
      162,
      234,
      133,
      30,
      128,
      42,
      243,
      117,
      168,
      133,
      201,
      98
    ]
  }
}
libs.js:80237 new BN(this.s).cmp(N_DIV_2) -1
libs.js:80246 ethUtil.bufferToInt(this.v) 92
libs.js:80250 v after subtract 82
libs.js:80254 early return 2 Error: Invalid signature v value
    at Object.exports.ecrecover (libs.js:80713)
    at Transaction.verifySignature (libs.js:80251)
    at app.js:1
    at <anonymous>
app.js:1 txSigned.verifySignature() false
```
so it appears that it is the `ethUtil.ecrecover` call that raises an exception

**Comment by eswak** [comment]
Looking at `ethUtil.ecrecover` function, I can see that `v` should have a value of `27 (0x1b)` or `28 (0x1c)` for the signature to be correct, but I get `91 (0x5b)` or `92 (0x5c)`. Maybe the problem is how I use the ledger library function.

**Comment by tmarkovski** [comment]
Maybe you need to reduce the 'v' by the chainId?
`v -= this._chainId * 2 + 8`

https://github.com/ethereumjs/ethereumjs-tx/blob/80045d78dff14800693916e841eae045339cff37/index.js#L217

**Comment by eswak** [comment]
I tried and it doesn't make much difference (with a `chainId` of `1` (eth main net), `91 - (1 * 2 + 8) = 81`, not equal to the needed `27`

**Comment by tmarkovski** [comment]
You're right. I see their API gave you `raw.v = '0x' + result.v; // "0x5b"`. I tried looking in their SDK to see if they do anything different, but this is returned from the server. What you can do is try to verify this is try to recover the public key from S and R using secp256k1 by passing 0 and 1 as V and compare that to the public key that belongs to the key pair trying to sign the tx. You should have access to their public key.

Check my work here.

https://github.com/tmarkovski/ethereumjs-tx-keyvault/blob/6500e598b09abb9ac32ce980f4a98c4bed414a26/index.js#L58

I'm doing something similar by signing a hash using Azure Key Vault. By default, Key Vault returns only S and R, so I find V by trying to recover it using 0 and 1, and comparing each result with the original public key.
In your case, if one of the recovered key matches the public key, I'd suggest to use your own logic and modify V accordingly as you need. Could it be that Nano's API assumes Kovan chain with ID 41?

**Comment by eswak** [comment]
Hi guys,

I managed to work things out !!

The raw transaction object needs to be initialized with the `chainId` in its `v` value before signature. As follows : 
```js
var raw = {
  "nonce": "0x1",
  "gasPrice": "0x2cb417800",
  "gasLimit": "0x5208",
  "to": "0x6ef71ca9cd708883e129559f5edbfb9d9d5c6148",
  "value": "0x5af3107a4000",
  "chainId": 1,

  // add these :
  "v": "0x01",
  "r": "0x00",
  "s": "0x00"
};

var txToSign = new ethereumjs.Tx(raw).serialize().toString('hex');

new ledger.eth(comm).signTransaction_async('44\'/60\'/0\'/0', txToSign).then(....
```

Otherwise, the signature was invalid.

This line from MEW code hinted me to the right direction : https://github.com/MyEtherWallet/MyEtherWallet/blob/00a84ec0c5f49d143e036c902c14496fa659593d/common/libs/wallet/deterministic/ledger.ts#L22

Then to create the transaction to broadcast, you should override the raw transaction's `v`, `r`, and `s` value with the one returned from the ledger library (so they contain actual signature values).

**Comment by eswak** [comment]
@tmarkovski I didn't have to do it like you suggested but that would've worked you're right ^^
An alternative check would've been to call `tx.verifySignature()` with different values of `v` until it would've been correct... lol

With the solution I commented, it gives correct values for `v`/`r`/`s` so no need for dirty workarounds

**Comment by arunsybex** [comment]
@eswak how to add "data" in raw hex ?

I tried like this 

{ "data":"0xc6427474000000000000000000000000be443e281a2d02fc76c7702c6143be660aa094b10000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","value":"0x0","gasLimit":"0x5208","gasPrice":"0x2cb417800","chainId":3,"to":"0x0aA8Ecf14Ba242966739E70635d91e14554B6fD7","nonce": "0x1","v":"0x01","r":"0x00","s":"0x00"}
