### ISSUE TITLE
Signing Contracts with ethereumjs-tx

### ISSUE THREAD

**Issue by danielsun174** [ethereumjs/ethereumjs-tx#9]
I am building a full-web ui which wont store any data at the ethereum-Provider.
Signing transactions with ethereumtx is working like wanted, but i can't figure out how to sign contracts.
When I run 'greeterContract.new( ... )' the signing happens at the provider. Is there any possibility to do this with this js-lib fully locally?

**Comment by wanderer** [comment]
I'm confused by what you mean by signing contracts. To create a contract you set the `data` field of the tx to the code of the contract you want to create. Then you sign that tx like you would normally.

**Comment by kumavis** [comment]
Seems like a lot of people are pursuing this pattern. I need to polish + publish + advertise my relevant stuff so people dont duplicate effort. some relevant stuff:
* https://github.com/metamask/provider-engine
* https://github.com/MetaMask/provider-engine/blob/master/subproviders/hooked-wallet.js
* https://github.com/consensys/lightwallet
* https://github.com/ConsenSys/hooked-web3-provider

**Comment by kumavis** [comment]
@danielsun174 I'm also about a month away from having a drop-in solution for dapp developers that works with or without Mist. Identities are accessible across dapps but safe from malicious code. Only caveat is that it only supports asynchronous web3 methods.

**Comment by danielsun174** [comment]
@wanderer when I opened this issue, my knowledge about ethereum was maybe too less. 
The javascript-solution looks something like this:
```javascript
var abi = greeterCompiled.greeter.info.abiDefinition
var greetString = "Hello World!"
var MyContract = web3.eth.contract(abi)
var contractData = MyContract.new.getData(greetString, {
    data: greeterCompiled.greeter.code
});

/* continue by signing rawTx with contractData as data-field */ 
```

@kumavis The Provider engine looks realy nice. I will check it out during the next week.


Issue is closed now.
