### ISSUE TITLE
'0x' should be automatically detected/prepended to transaction data

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-tx#90]
Ran into this today and it took a little while to figure out because ethereumjs-tx was failing silently in this case.  I'll see if there are other fields that have the same issue.

**Comment by alcuadrado** [comment]
Hi @jwasinger,

A possible fix local to this library was developed in #144, but after discussing it, we decided to fix this in `ethereumjs-util`. This alternative fix has already been merged but hasn't been released yet. You can take a look at it here: https://github.com/ethereumjs/ethereumjs-util/pull/197

**Comment by alcuadrado** [comment]
I'm closing this issue. If someone encounters this problem after version 2 is released please open a new issue.
