### ISSUE TITLE
use Buffer in simple html pages

### ISSUE THREAD

**Issue by shahzadthathal** [ethereumjs/ethereumjs-tx#95]
Is there any way to use Buffer in simple web page actually I don't have nodejs app.
I included ethereumjs-tx in my app buy Buffer is not working.

This is working but Buffer class not found.
<script src="{{ asset('browser-builds-master/dist/ethereumjs-tx/ethereumjs-tx-1.3.3.min.js') }}"></script>

Thanks in advance

**Comment by holgerd77** [comment]
Please keep the discussion on the single issue in ``browser-builds``, this gets too fragmented otherwise.
